name: coin-ft
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - libexpat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.3
  - python=3.10.19
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
    - certifi==2025.11.12
    - charset-normalizer==3.4.4
    - click==8.3.1
    - colorama==0.4.6
    - contourpy==1.3.2
    - cycler==0.12.1
    - deprecation==2.1.0
    - fonttools==4.61.1
    - h5py==3.15.1
    - hightime==1.0.0
    - idna==3.11
    - kiwisolver==1.4.9
    - matplotlib==3.10.8
    - nidaqmx==1.3.0
    - nitypes==1.1.0.dev1
    - numpy==2.2.6
    - packaging==25.0
    - pillow==12.0.0
    - pyparsing==3.2.5
    - pyserial==3.5
    - python-dateutil==2.9.0.post0
    - python-decouple==3.8
    - requests==2.32.5
    - scipy==1.15.3
    - six==1.17.0
    - typing-extensions==4.15.0
    - tzdata==2025.3
    - tzlocal==5.3.1
    - urllib3==2.6.2
prefix: C:\Users\BDML\anaconda3\envs\coin-ft
