name: coin-ft
channels:
  - pytorch       
  - conda-forge   
  - defaults      
dependencies:
  - python=3.10
  - numpy=2.2
  - scipy=1.15
  - matplotlib=3.10
  - h5py=3.15
  - pytorch
  - onnx
  - pip           
  
  - pip:
    - pyserial==3.5
    - python-decouple==3.8
    - tqdm  
    - nidaqmx==1.3.0