name: coin-ft
channels:
  - pytorch  
  - conda-forge
  - defaults      
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - h5py=3.15
  - pytorch
  - pip           
  
  - pip:
    - onnx
    - onnxruntime
    - pandas
    - openpyxl
    - pyserial==3.5
    - python-decouple==3.8
    - tqdm  
    - nidaqmx==1.3.0